import { StyleSheet } from "@react-pdf/renderer";

export const pdfColors = {
  white: "#FFFFFF",
  ink: "#26231F",
  text: "#34302A",
  muted: "#6F675E",
  line: "#D9D0C0",
  lineSoft: "#ECE5DA",
  gold: "#B98A3A",
  sand: "#F3ECDF",
  volcanic: "#5C2B23",
  volcanicDark: "#2B2724",
  salitre: "#527F84",
  salitreSoft: "#E7F0F0",
  stone: "#403A34",
  smoke: "#F8F6F2",
  blackGlass: "rgba(18, 16, 14, 0.34)",
  whiteGlass: "rgba(255, 255, 255, 0.86)",
  ivoryGlass: "rgba(255, 250, 240, 0.86)",
  darkGlass: "rgba(22, 18, 15, 0.68)",
  webPrimary: "#2F2A24",
};

export const styles = StyleSheet.create({
  page: {
    paddingTop: 80,
    paddingRight: 56,
    paddingBottom: 56,
    paddingLeft: 56,
    backgroundColor: pdfColors.white,
    color: pdfColors.text,
    fontFamily: "Helvetica",
    fontSize: 10,
    lineHeight: 1.55,
  },
  indexPage: {
    paddingTop: 48,
    paddingBottom: 42,
  },
  coverPage: {
    backgroundColor: pdfColors.white,
    color: pdfColors.text,
    fontFamily: "Helvetica",
  },
  footer: {
    position: "absolute",
    left: 56,
    right: 56,
    bottom: 18,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: pdfColors.lineSoft,
    color: pdfColors.muted,
    fontSize: 8.8,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerTitle: {
    color: pdfColors.volcanicDark,
    fontFamily: "Helvetica-Bold",
    fontSize: 8,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  footerPageNumber: {
    color: pdfColors.volcanicDark,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 0.7,
  },
  pageIdentityMarker: {
    position: "absolute",
    top: 31,
    left: 56,
    height: 22,
    flexDirection: "row",
    alignItems: "center",
  },
  pageIdentityRule: {
    width: 26,
    height: 1,
    marginRight: 9,
    backgroundColor: pdfColors.gold,
  },
  pageIdentityRuleDark: {
    backgroundColor: "rgba(255,255,255,0.72)",
  },
  pageIdentityName: {
    color: pdfColors.volcanicDark,
    fontFamily: "Helvetica-Bold",
    fontSize: 6.8,
    letterSpacing: 1.35,
    textTransform: "uppercase",
  },
  pageIdentityNumber: {
    marginLeft: 10,
    color: pdfColors.volcanicDark,
    fontFamily: "Helvetica-Bold",
    fontSize: 7,
    letterSpacing: 0.8,
  },
  pageIdentityTextDark: {
    color: pdfColors.white,
  },
  pageHeader: {
    position: "absolute",
    top: 28,
    right: 54,
    height: 32,
    flexDirection: "row",
    alignItems: "center",
  },
  pageHeaderText: {
    marginRight: 10,
    color: pdfColors.volcanicDark,
    fontSize: 8,
    letterSpacing: 2.1,
    textTransform: "uppercase",
  },
  pageHeaderLogo: {
    width: 54,
    height: 30,
    objectFit: "contain",
    opacity: 0.55,
  },
  pageAccent: {
    position: "absolute",
    top: 88,
    left: 36,
    bottom: 56,
    width: 1,
    backgroundColor: pdfColors.lineSoft,
  },
  coverHeroImage: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: 590,
    objectFit: "cover",
  },
  coverImageOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 590,
    backgroundColor: pdfColors.blackGlass,
  },
  coverImageWash: {
    position: "absolute",
    top: 530,
    left: 0,
    right: 0,
    height: 82,
    backgroundColor: pdfColors.whiteGlass,
  },
  coverRule: {
    width: 86,
    height: 2,
    backgroundColor: pdfColors.gold,
    marginTop: 36,
    marginBottom: 32,
  },
  coverTitleBlock: {
    position: "absolute",
    left: 54,
    right: 74,
    top: 282,
    paddingTop: 22,
    paddingRight: 24,
    paddingBottom: 22,
    paddingLeft: 24,
    borderWidth: 1,
    borderColor: "rgba(217, 208, 192, 0.62)",
    backgroundColor: pdfColors.ivoryGlass,
  },
  coverEyebrow: {
    fontSize: 8.5,
    color: pdfColors.gold,
    letterSpacing: 2.7,
    textTransform: "uppercase",
    marginBottom: 14,
  },
  coverTitle: {
    maxWidth: 410,
    fontFamily: "Times-Bold",
    fontSize: 31,
    lineHeight: 1.05,
    color: pdfColors.ink,
    textTransform: "uppercase",
  },
  coverSubtitle: {
    marginTop: 16,
    maxWidth: 395,
    fontSize: 10.8,
    lineHeight: 1.62,
    color: pdfColors.text,
  },
  coverMeta: {
    marginTop: 70,
    paddingTop: 18,
    borderTopWidth: 1,
    borderTopColor: pdfColors.line,
  },
  coverInfoPanel: {
    position: "absolute",
    left: 54,
    right: 54,
    top: 636,
    paddingTop: 20,
    paddingRight: 22,
    paddingBottom: 18,
    paddingLeft: 22,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: pdfColors.line,
    borderBottomColor: pdfColors.lineSoft,
    backgroundColor: pdfColors.white,
    flexDirection: "row",
  },
  coverInfoMain: {
    width: "38%",
    paddingRight: 22,
    borderRightWidth: 1,
    borderRightColor: pdfColors.lineSoft,
  },
  coverInfoGrid: {
    width: "62%",
    paddingLeft: 22,
  },
  coverInfoItem: {
    marginBottom: 10,
  },
  coverLabel: {
    marginBottom: 5,
    color: pdfColors.gold,
    fontSize: 7.6,
    letterSpacing: 1.6,
    textTransform: "uppercase",
  },
  coverStudentName: {
    fontFamily: "Times-Bold",
    fontSize: 18,
    lineHeight: 1.15,
    color: pdfColors.ink,
  },
  coverDate: {
    marginTop: 9,
    color: pdfColors.muted,
    fontSize: 9,
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  coverMetaText: {
    color: pdfColors.text,
    fontSize: 9.4,
    lineHeight: 1.4,
  },
  topKicker: {
    fontSize: 8,
    color: pdfColors.gold,
    letterSpacing: 2.2,
    textTransform: "uppercase",
    marginBottom: 9,
  },
  h1: {
    fontFamily: "Times-Bold",
    fontSize: 31,
    lineHeight: 1.08,
    color: pdfColors.ink,
    marginBottom: 10,
  },
  h2: {
    fontFamily: "Times-Bold",
    fontSize: 15.8,
    lineHeight: 1.2,
    color: pdfColors.ink,
    marginBottom: 8,
  },
  h3: {
    fontFamily: "Times-Bold",
    fontSize: 12,
    color: pdfColors.volcanicDark,
    marginBottom: 7,
  },
  lead: {
    fontSize: 10.7,
    lineHeight: 1.62,
    color: pdfColors.text,
    marginBottom: 17,
  },
  paragraph: {
    fontSize: 9.4,
    lineHeight: 1.58,
    color: pdfColors.text,
    marginBottom: 10,
  },
  fullSection: {
    marginTop: 18,
    paddingTop: 12,
  },
  sectionKicker: {
    marginBottom: 7,
    color: pdfColors.gold,
    fontSize: 7.6,
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
  sectionLead: {
    marginBottom: 13,
    color: pdfColors.text,
    fontSize: 10,
    lineHeight: 1.55,
  },
  subsectionBreak: {
    marginTop: 18,
    paddingTop: 13,
  },
  mutedText: {
    color: pdfColors.muted,
  },
  section: {
    marginTop: 18,
    paddingTop: 13,
    borderTopWidth: 1,
    borderTopColor: pdfColors.line,
  },
  titleCluster: {
    marginBottom: 12,
  },
  titleRule: {
    width: 54,
    height: 2,
    marginTop: 6,
    backgroundColor: pdfColors.gold,
  },
  slimRule: {
    height: 1,
    backgroundColor: pdfColors.line,
    marginTop: 14,
    marginBottom: 14,
  },
  accentLine: {
    width: 42,
    height: 2,
    backgroundColor: pdfColors.gold,
    marginBottom: 14,
  },
  indexList: {
    marginTop: 14,
    borderTopWidth: 1,
    borderTopColor: pdfColors.line,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  indexRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "48%",
    minHeight: 46,
    marginRight: "4%",
    paddingTop: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.lineSoft,
  },
  indexRowEven: {
    marginRight: 0,
  },
  indexNumber: {
    width: 32,
    color: pdfColors.gold,
    fontFamily: "Times-Bold",
    fontSize: 12,
    letterSpacing: 1,
  },
  indexTextGroup: {
    flex: 1,
    paddingRight: 8,
  },
  indexTitle: {
    fontFamily: "Times-Bold",
    fontSize: 10.6,
    color: pdfColors.ink,
    marginBottom: 3,
  },
  indexTitleLink: {
    color: pdfColors.ink,
    textDecoration: "none",
  },
  indexSubtitle: {
    color: pdfColors.muted,
    fontSize: 7.1,
    lineHeight: 1.25,
  },
  indexAction: {
    width: 22,
    color: pdfColors.salitre,
    fontSize: 6.8,
    letterSpacing: 1.3,
    textDecoration: "none",
    textTransform: "uppercase",
  },
  figure: {
    marginTop: 12,
    marginBottom: 12,
  },
  figureFeature: {
    marginTop: 8,
    marginBottom: 14,
  },
  heroImage: {
    width: "100%",
    height: 210,
    objectFit: "cover",
  },
  wideImage: {
    width: "100%",
    height: 190,
    objectFit: "cover",
  },
  featureImage: {
    width: "100%",
    height: 198,
    objectFit: "cover",
  },
  imageContain: {
    width: "100%",
    height: 190,
    objectFit: "contain",
    backgroundColor: pdfColors.smoke,
    borderWidth: 1,
    borderColor: pdfColors.lineSoft,
  },
  imageGridContain: {
    width: "100%",
    height: 118,
    objectFit: "contain",
    backgroundColor: pdfColors.smoke,
    borderWidth: 1,
    borderColor: pdfColors.lineSoft,
  },
  imageCaption: {
    marginTop: 6,
    paddingLeft: 10,
    borderLeftWidth: 1,
    borderLeftColor: pdfColors.gold,
    color: pdfColors.muted,
    fontSize: 8.5,
    lineHeight: 1.28,
  },
  twoColumns: {
    flexDirection: "row",
    marginTop: 14,
  },
  columnLeft: {
    width: "48%",
    marginRight: "4%",
  },
  columnRight: {
    width: "48%",
  },
  editorialColumns: {
    flexDirection: "row",
    marginTop: 10,
  },
  editorialMainColumn: {
    width: "58%",
    marginRight: "6%",
  },
  editorialAsideColumn: {
    width: "36%",
  },
  highlightBlock: {
    marginTop: 10,
    paddingTop: 10,
    paddingRight: 11,
    paddingBottom: 5,
    paddingLeft: 11,
    backgroundColor: pdfColors.smoke,
  },
  bulletRow: {
    flexDirection: "row",
    marginBottom: 6,
  },
  bulletDot: {
    width: 10,
    color: pdfColors.gold,
    fontSize: 12.5,
    lineHeight: 1.4,
  },
  bulletText: {
    flex: 1,
    color: pdfColors.text,
    fontSize: 8.8,
    lineHeight: 1.42,
  },
  infoBand: {
    marginTop: 12,
    paddingTop: 11,
    paddingRight: 13,
    paddingBottom: 10,
    paddingLeft: 13,
    borderLeftWidth: 2,
    borderLeftColor: pdfColors.gold,
    backgroundColor: pdfColors.smoke,
  },
  cardGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
  },
  editorialCard: {
    marginRight: "4%",
    marginBottom: 10,
    paddingTop: 10,
    paddingRight: 11,
    paddingBottom: 10,
    paddingLeft: 11,
    backgroundColor: pdfColors.smoke,
  },
  editorialCardHalf: {
    width: "48%",
  },
  editorialCardThird: {
    width: "30.66%",
  },
  cardNoMargin: {
    marginRight: 0,
  },
  smallLabel: {
    marginBottom: 5,
    color: pdfColors.salitre,
    fontSize: 7,
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  cardTitle: {
    marginBottom: 5,
    color: pdfColors.ink,
    fontFamily: "Times-Bold",
    fontSize: 12,
    lineHeight: 1.16,
  },
  cardText: {
    color: pdfColors.text,
    fontSize: 8.4,
    lineHeight: 1.42,
    marginBottom: 6,
  },
  numberedList: {
    marginTop: 9,
  },
  numberedRow: {
    flexDirection: "row",
    paddingTop: 7,
    paddingBottom: 7,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.lineSoft,
  },
  numberedIndex: {
    width: 28,
    color: pdfColors.gold,
    fontFamily: "Times-Bold",
    fontSize: 10,
  },
  numberedText: {
    flex: 1,
    color: pdfColors.text,
    fontSize: 8.8,
    lineHeight: 1.42,
  },
  imageTextFeature: {
    marginTop: 8,
    marginBottom: 14,
    flexDirection: "row",
  },
  imageTextPhoto: {
    width: "44%",
    height: 165,
    objectFit: "cover",
  },
  imageTextBody: {
    width: "56%",
    paddingTop: 2,
    paddingLeft: 18,
  },
  conceptFeature: {
    marginTop: 8,
    marginBottom: 14,
  },
  conceptTopRow: {
    flexDirection: "row",
    marginBottom: 8,
  },
  conceptLogoImage: {
    width: "43%",
    height: 160,
    objectFit: "contain",
    backgroundColor: pdfColors.volcanicDark,
  },
  conceptTextColumn: {
    width: "57%",
    paddingTop: 2,
    paddingLeft: 18,
  },
  reinterpretationPageHeader: {
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.lineSoft,
    paddingBottom: 9,
  },
  reinterpretationCounter: {
    color: pdfColors.salitre,
    fontFamily: "Helvetica-Bold",
    fontSize: 7,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  reinterpretationSpread: {
    flexDirection: "row",
    marginTop: 10,
  },
  reinterpretationImagePanel: {
    width: "61%",
    marginRight: "5%",
  },
  reinterpretationFullImage: {
    width: "100%",
    height: 560,
    objectFit: "contain",
  },
  reinterpretationInfoPanel: {
    width: "34%",
    paddingTop: 44,
  },
  reinterpretationTitle: {
    color: pdfColors.ink,
    fontFamily: "Times-Bold",
    fontSize: 25,
    lineHeight: 1.05,
    marginBottom: 12,
  },
  reinterpretationComponentBlock: {
    marginTop: 16,
    paddingTop: 13,
    borderTopWidth: 1,
    borderTopColor: pdfColors.line,
  },
  reinterpretationComponentLabel: {
    marginBottom: 7,
    color: pdfColors.gold,
    fontFamily: "Helvetica-Bold",
    fontSize: 7,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  imageCardGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
  },
  imageEditorialCard: {
    width: "48%",
    marginRight: "4%",
    marginBottom: 12,
    backgroundColor: pdfColors.white,
  },
  imageCardPhoto: {
    width: "100%",
    height: 118,
    objectFit: "cover",
  },
  imageCardBody: {
    paddingTop: 9,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
  },
  logoVersionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
  },
  logoVersionCard: {
    width: "48%",
    marginRight: "4%",
    marginBottom: 12,
    paddingBottom: 9,
    backgroundColor: pdfColors.white,
  },
  logoVersionCardEven: {
    marginRight: 0,
  },
  logoVersionFrame: {
    height: 92,
    paddingTop: 12,
    paddingRight: 12,
    paddingBottom: 12,
    paddingLeft: 12,
    backgroundColor: pdfColors.volcanicDark,
  },
  logoVersionImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
  },
  detailCards: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 9,
  },
  detailCard: {
    width: "48%",
    marginRight: "4%",
    marginBottom: 13,
    paddingTop: 12,
    paddingRight: 13,
    paddingBottom: 10,
    paddingLeft: 13,
    borderWidth: 1,
    borderColor: pdfColors.lineSoft,
    backgroundColor: pdfColors.white,
  },
  narrativeCard: {
    marginBottom: 12,
    paddingTop: 12,
    paddingRight: 13,
    paddingBottom: 10,
    paddingLeft: 13,
    borderLeftWidth: 2,
    borderLeftColor: pdfColors.salitre,
    backgroundColor: pdfColors.smoke,
  },
  detailCardHeader: {
    flexDirection: "row",
    marginBottom: 9,
  },
  technicalHeader: {
    flexDirection: "row",
    marginBottom: 10,
  },
  detailIndex: {
    width: 34,
    color: pdfColors.gold,
    fontFamily: "Times-Bold",
    fontSize: 15,
  },
  detailTitleGroup: {
    flex: 1,
  },
  detailTitle: {
    color: pdfColors.ink,
    fontFamily: "Times-Bold",
    fontSize: 14,
    lineHeight: 1.16,
  },
  detailLabel: {
    marginTop: 7,
    marginBottom: 3,
    color: pdfColors.gold,
    fontSize: 7.2,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  technicalCard: {
    marginTop: 12,
    marginBottom: 16,
    paddingTop: 13,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    backgroundColor: pdfColors.smoke,
  },
  technicalImage: {
    width: "100%",
    height: 148,
    objectFit: "cover",
    marginBottom: 10,
  },
  mediaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 8,
    marginBottom: 12,
  },
  mediaCard: {
    width: "30.66%",
    marginRight: "4%",
    marginBottom: 12,
    paddingBottom: 8,
    borderWidth: 1,
    borderColor: pdfColors.lineSoft,
    backgroundColor: pdfColors.white,
  },
  mediaImage: {
    width: "100%",
    height: 92,
    objectFit: "cover",
    marginBottom: 8,
  },
  mediaTitle: {
    paddingRight: 8,
    paddingLeft: 8,
    color: pdfColors.ink,
    fontFamily: "Times-Bold",
    fontSize: 9.6,
    lineHeight: 1.2,
  },
  qrRecipeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
  },
  qrRecipeCard: {
    width: "30.66%",
    marginRight: "4%",
    marginBottom: 12,
    paddingTop: 9,
    paddingRight: 8,
    paddingBottom: 9,
    paddingLeft: 8,
    backgroundColor: pdfColors.smoke,
    flexDirection: "row",
  },
  qrRecipeImage: {
    width: 54,
    height: 54,
    backgroundColor: pdfColors.white,
  },
  qrRecipeText: {
    flex: 1,
    paddingLeft: 8,
  },
  phaseHeader: {
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.lineSoft,
  },
  phaseNumber: {
    color: pdfColors.salitre,
    fontSize: 8.5,
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  phaseTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  phaseBadge: {
    width: 50,
    marginRight: 16,
    paddingTop: 9,
    paddingBottom: 9,
    textAlign: "center",
    color: pdfColors.white,
    backgroundColor: pdfColors.volcanicDark,
    fontFamily: "Times-Bold",
    fontSize: 18,
  },
  phaseTitle: {
    flex: 1,
    fontFamily: "Times-Bold",
    fontSize: 27,
    lineHeight: 1.08,
    color: pdfColors.ink,
  },
  phaseIntroBlock: {
    marginBottom: 4,
  },
  subsection: {
    marginBottom: 10,
    paddingLeft: 12,
  },
  subsectionRule: {
    width: 26,
    height: 1,
    marginBottom: 8,
    backgroundColor: pdfColors.gold,
  },
  imageGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
  },
  imageGridItem: {
    width: "48%",
    marginRight: "4%",
    marginBottom: 12,
  },
  imageGridItemLast: {
    marginRight: 0,
  },
  imageThumb: {
    width: "100%",
    height: 104,
    objectFit: "cover",
  },
  menuGalleryPage: {
    marginTop: 12,
  },
  menuGalleryItem: {
    marginBottom: 18,
  },
  menuGalleryImage: {
    width: "100%",
    height: 274,
    objectFit: "contain",
    backgroundColor: pdfColors.smoke,
    borderWidth: 1,
    borderColor: pdfColors.lineSoft,
  },
  tableEditorialHeader: {
    marginTop: 4,
    marginBottom: 2,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  tableContinuationLabel: {
    color: pdfColors.salitre,
    fontFamily: "Helvetica-Bold",
    fontSize: 7,
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  table: {
    marginTop: 10,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: pdfColors.sand,
  },
  tableRow: {
    flexDirection: "row",
  },
  tableCell: {
    paddingTop: 6,
    paddingRight: 7,
    paddingBottom: 6,
    paddingLeft: 7,
    borderRightWidth: 1,
    borderRightColor: pdfColors.line,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.line,
    fontSize: 8,
    lineHeight: 1.35,
  },
  tableHeadCell: {
    color: pdfColors.volcanicDark,
    fontFamily: "Helvetica-Bold",
    fontSize: 7.3,
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  menuBlock: {
    marginTop: 9,
    paddingTop: 9,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
    borderTopWidth: 1,
    borderTopColor: pdfColors.lineSoft,
    backgroundColor: pdfColors.smoke,
  },
  menuTitle: {
    fontFamily: "Times-Bold",
    fontSize: 12.5,
    color: pdfColors.ink,
    marginBottom: 3,
  },
  menuMeta: {
    color: pdfColors.gold,
    fontSize: 7.8,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 5,
  },
  dishBlock: {
    width: "48%",
    marginRight: "4%",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: pdfColors.lineSoft,
    backgroundColor: pdfColors.white,
  },
  dishBlockEven: {
    marginRight: 0,
  },
  dishImage: {
    width: "100%",
    height: 98,
    objectFit: "cover",
  },
  dishBody: {
    paddingTop: 8,
    paddingRight: 9,
    paddingBottom: 9,
    paddingLeft: 9,
  },
  dishName: {
    fontFamily: "Times-Bold",
    fontSize: 11.6,
    color: pdfColors.ink,
    marginBottom: 4,
  },
  dishMeta: {
    fontSize: 7.1,
    color: pdfColors.salitre,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 5,
  },
  dishText: {
    fontSize: 7.8,
    lineHeight: 1.35,
    color: pdfColors.text,
  },
  dishTechnique: {
    marginTop: 5,
    color: pdfColors.volcanicDark,
    fontSize: 7.7,
    lineHeight: 1.35,
  },
  dafoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
  },
  dafoItem: {
    width: "48%",
    marginRight: "4%",
    marginBottom: 10,
    paddingTop: 9,
    paddingRight: 10,
    paddingBottom: 6,
    paddingLeft: 10,
    borderTopWidth: 2,
    borderTopColor: pdfColors.salitre,
    backgroundColor: pdfColors.smoke,
  },
  dafoItemEven: {
    marginRight: 0,
  },
  budgetSheet: {
    marginTop: 12,
    paddingTop: 18,
    paddingRight: 18,
    paddingBottom: 18,
    paddingLeft: 18,
    backgroundColor: pdfColors.smoke,
  },
  budgetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.line,
  },
  budgetKicker: {
    color: pdfColors.gold,
    fontSize: 7.2,
    letterSpacing: 1.6,
    textTransform: "uppercase",
    marginBottom: 5,
  },
  budgetTitle: {
    color: pdfColors.ink,
    fontFamily: "Times-Bold",
    fontSize: 25,
    lineHeight: 1.05,
  },
  budgetSubtitle: {
    marginTop: 4,
    color: pdfColors.muted,
    fontSize: 8.5,
  },
  budgetMetaBox: {
    width: 150,
    paddingTop: 9,
    paddingRight: 11,
    paddingBottom: 8,
    paddingLeft: 11,
    backgroundColor: pdfColors.white,
  },
  budgetMetaLabel: {
    color: pdfColors.gold,
    fontSize: 6.5,
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  budgetMetaValue: {
    marginBottom: 6,
    color: pdfColors.ink,
    fontFamily: "Helvetica-Bold",
    fontSize: 8.5,
  },
  budgetColumns: {
    flexDirection: "row",
    marginTop: 14,
  },
  budgetNoteCard: {
    width: "48%",
    marginRight: "4%",
    paddingTop: 10,
    paddingRight: 11,
    paddingBottom: 7,
    paddingLeft: 11,
    backgroundColor: pdfColors.white,
  },
  budgetNoteTitle: {
    marginBottom: 5,
    color: pdfColors.ink,
    fontFamily: "Times-Bold",
    fontSize: 11,
  },
  budgetNoteText: {
    marginBottom: 4,
    color: pdfColors.text,
    fontSize: 7.1,
    lineHeight: 1.25,
  },
  budgetBlock: {
    marginTop: 14,
    paddingTop: 10,
    paddingRight: 12,
    paddingBottom: 12,
    paddingLeft: 12,
    backgroundColor: pdfColors.white,
  },
  budgetSectionTitle: {
    marginBottom: 4,
    color: pdfColors.ink,
    fontFamily: "Times-Bold",
    fontSize: 12,
  },
  budgetTotalRow: {
    marginTop: 8,
    paddingTop: 9,
    paddingRight: 10,
    paddingBottom: 9,
    paddingLeft: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: pdfColors.volcanicDark,
  },
  budgetTotalLabel: {
    color: pdfColors.white,
    fontFamily: "Helvetica-Bold",
    fontSize: 8.5,
  },
  budgetTotalValue: {
    color: pdfColors.gold,
    fontFamily: "Helvetica-Bold",
    fontSize: 10,
  },
  budgetLegalNote: {
    marginTop: 12,
    paddingTop: 10,
    paddingRight: 12,
    paddingBottom: 8,
    paddingLeft: 12,
    borderLeftWidth: 2,
    borderLeftColor: pdfColors.gold,
    backgroundColor: pdfColors.white,
  },
  recipeCoverGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 22,
    marginBottom: 18,
  },
  recipeCoverCard: {
    width: "48%",
    marginRight: "4%",
    marginBottom: 14,
    paddingTop: 14,
    paddingRight: 16,
    paddingBottom: 14,
    paddingLeft: 16,
    backgroundColor: pdfColors.smoke,
  },
  recipeCoverNumber: {
    color: pdfColors.gold,
    fontFamily: "Times-Bold",
    fontSize: 15,
    marginBottom: 6,
  },
  recipeCoverTitle: {
    color: pdfColors.ink,
    fontFamily: "Times-Bold",
    fontSize: 18,
    lineHeight: 1.1,
  },
  recipeCoverMeta: {
    marginTop: 6,
    marginBottom: 7,
    color: pdfColors.salitre,
    fontSize: 7.5,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  recipePage: {
    paddingTop: 52,
    paddingRight: 36,
    paddingBottom: 34,
    paddingLeft: 36,
    backgroundColor: pdfColors.white,
    color: pdfColors.text,
    fontFamily: "Helvetica",
    fontSize: 7,
    lineHeight: 1.23,
  },
  recipePageHeader: {
    position: "absolute",
    top: 20,
    right: 36,
    height: 24,
    flexDirection: "row",
    alignItems: "center",
  },
  recipePageHeaderText: {
    marginRight: 8,
    color: pdfColors.volcanicDark,
    fontSize: 7,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  recipePageHeaderLogo: {
    width: 46,
    height: 24,
    objectFit: "contain",
    opacity: 0.55,
  },
  recipeFooter: {
    position: "absolute",
    left: 36,
    right: 36,
    bottom: 14,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: pdfColors.lineSoft,
    color: pdfColors.muted,
    fontSize: 7,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  recipeTopRow: {
    flexDirection: "row",
    marginBottom: 12,
  },
  recipePhotoBlock: {
    width: 306,
    marginRight: 18,
  },
  recipePhoto: {
    width: 306,
    height: 172.125,
    objectFit: "cover",
    backgroundColor: pdfColors.smoke,
  },
  recipePhotoCaption: {
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 8,
    paddingRight: 8,
    backgroundColor: pdfColors.volcanicDark,
  },
  recipePhotoCaptionText: {
    color: pdfColors.white,
    fontSize: 5.8,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  recipeIntroBlockLandscape: {
    flex: 1,
    paddingTop: 2,
  },
  recipeKicker: {
    color: pdfColors.gold,
    fontSize: 7,
    letterSpacing: 1.4,
    textTransform: "uppercase",
    marginBottom: 7,
  },
  recipeTitle: {
    color: pdfColors.ink,
    fontFamily: "Times-Bold",
    fontSize: 24,
    lineHeight: 1.02,
    marginBottom: 7,
  },
  recipeMenuText: {
    color: pdfColors.salitre,
    fontFamily: "Helvetica-Bold",
    fontSize: 7.2,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  recipeLeadText: {
    color: pdfColors.text,
    fontSize: 8,
    lineHeight: 1.32,
    marginBottom: 10,
  },
  recipeQrRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 8,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
    backgroundColor: pdfColors.smoke,
  },
  recipeQrImage: {
    width: 58,
    height: 58,
    backgroundColor: pdfColors.white,
  },
  recipeQrText: {
    flex: 1,
    marginLeft: 10,
  },
  recipeUrl: {
    color: pdfColors.salitre,
    fontSize: 6.2,
    lineHeight: 1.25,
    textDecoration: "none",
  },
  recipePassword: {
    marginTop: 4,
    color: pdfColors.ink,
    fontFamily: "Helvetica-Bold",
    fontSize: 7,
  },
  recipeColumns: {
    flexDirection: "row",
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: pdfColors.lineSoft,
  },
  recipeColumnLarge: {
    width: "25%",
    marginRight: "2%",
  },
  recipeColumn: {
    width: "24%",
    marginRight: "2%",
  },
  recipeColumnLast: {
    width: "21%",
  },
  recipeColumnTitle: {
    marginBottom: 7,
    color: pdfColors.ink,
    fontFamily: "Times-Bold",
    fontSize: 11.5,
    lineHeight: 1.05,
  },
  recipeKeyValue: {
    marginBottom: 5,
  },
  recipeLabel: {
    marginBottom: 2,
    color: pdfColors.gold,
    fontSize: 5.4,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  recipeText: {
    color: pdfColors.text,
    fontSize: 5.9,
    lineHeight: 1.22,
  },
  recipeIngredientColumns: {
    flexDirection: "row",
    marginBottom: 5,
  },
  recipeIngredientColumn: {
    width: "49%",
    marginRight: "2%",
  },
  recipeIngredientColumnLast: {
    marginRight: 0,
  },
  recipeIngredientRow: {
    marginBottom: 2.2,
  },
  recipeIngredientName: {
    color: pdfColors.ink,
    fontFamily: "Helvetica-Bold",
    fontSize: 5.4,
    lineHeight: 1.08,
  },
  recipeIngredientAmount: {
    color: pdfColors.muted,
    fontSize: 5.2,
    lineHeight: 1.08,
  },
  qrAccessCard: {
    marginTop: 26,
    paddingTop: 28,
    paddingRight: 28,
    paddingBottom: 28,
    paddingLeft: 28,
    borderWidth: 1,
    borderColor: pdfColors.line,
    backgroundColor: pdfColors.smoke,
    flexDirection: "row",
    alignItems: "center",
  },
  projectQrImage: {
    width: 180,
    height: 180,
    backgroundColor: pdfColors.white,
  },
  qrAccessText: {
    flex: 1,
    marginLeft: 28,
  },
  qrLabel: {
    marginTop: 14,
    marginBottom: 5,
    color: pdfColors.gold,
    fontSize: 8,
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  qrUrl: {
    color: pdfColors.salitre,
    fontSize: 11,
    lineHeight: 1.45,
    textDecoration: "none",
  },
  qrPassword: {
    color: pdfColors.ink,
    fontFamily: "Helvetica-Bold",
    fontSize: 15,
    letterSpacing: 0.8,
  },
  ceoClosingPage: {
    backgroundColor: pdfColors.webPrimary,
    color: pdfColors.white,
    fontFamily: "Helvetica",
  },
  ceoClosingCenter: {
    position: "absolute",
    top: 142,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  ceoPhoto: {
    width: 260,
    height: 260,
    objectFit: "cover",
    borderWidth: 1,
    borderColor: pdfColors.gold,
  },
  ceoCaption: {
    marginTop: 18,
    color: pdfColors.white,
    fontFamily: "Times-Bold",
    fontSize: 16,
    letterSpacing: 0.5,
  },
  ceoFooter: {
    position: "absolute",
    left: 56,
    right: 56,
    bottom: 18,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.28)",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  ceoFooterText: {
    color: pdfColors.white,
    fontFamily: "Helvetica-Bold",
    fontSize: 8,
    letterSpacing: 1.4,
  },
});
