import { StyleSheet } from "@react-pdf/renderer";

export const pdfColors = {
  white: "#FFFFFF",
  ink: "#26231F",
  text: "#34302A",
  muted: "#6F675E",
  line: "#D9D0C0",
  lineSoft: "#ECE5DA",
  gold: "#B98A3A",
  sand: "#F3ECDF",
  volcanic: "#5C2B23",
  volcanicDark: "#2B2724",
  salitre: "#527F84",
  salitreSoft: "#E7F0F0",
};

export const styles = StyleSheet.create({
  page: {
    paddingTop: 52,
    paddingRight: 52,
    paddingBottom: 48,
    paddingLeft: 52,
    backgroundColor: pdfColors.white,
    color: pdfColors.text,
    fontFamily: "Helvetica",
    fontSize: 10,
    lineHeight: 1.55,
  },
  coverPage: {
    paddingTop: 64,
    paddingRight: 58,
    paddingBottom: 58,
    paddingLeft: 58,
    backgroundColor: pdfColors.white,
    color: pdfColors.text,
    fontFamily: "Helvetica",
  },
  footer: {
    position: "absolute",
    left: 52,
    right: 52,
    bottom: 24,
    paddingTop: 7,
    borderTopWidth: 1,
    borderTopColor: pdfColors.lineSoft,
    color: pdfColors.muted,
    fontSize: 8,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerTitle: {
    color: pdfColors.volcanicDark,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  coverRule: {
    width: 86,
    height: 2,
    backgroundColor: pdfColors.gold,
    marginTop: 36,
    marginBottom: 32,
  },
  coverLogo: {
    width: 145,
    height: 88,
    objectFit: "contain",
  },
  coverEyebrow: {
    marginTop: 34,
    fontSize: 9,
    color: pdfColors.gold,
    letterSpacing: 2.2,
    textTransform: "uppercase",
  },
  coverTitle: {
    marginTop: 18,
    maxWidth: 410,
    fontFamily: "Times-Bold",
    fontSize: 42,
    lineHeight: 1.06,
    color: pdfColors.ink,
  },
  coverSubtitle: {
    marginTop: 18,
    maxWidth: 340,
    fontSize: 12,
    lineHeight: 1.65,
    color: pdfColors.muted,
  },
  coverMeta: {
    marginTop: 70,
    paddingTop: 18,
    borderTopWidth: 1,
    borderTopColor: pdfColors.line,
  },
  coverMetaText: {
    color: pdfColors.text,
    fontSize: 10,
    marginBottom: 5,
  },
  topKicker: {
    fontSize: 8,
    color: pdfColors.gold,
    letterSpacing: 1.8,
    textTransform: "uppercase",
    marginBottom: 10,
  },
  h1: {
    fontFamily: "Times-Bold",
    fontSize: 30,
    lineHeight: 1.14,
    color: pdfColors.ink,
    marginBottom: 16,
  },
  h2: {
    fontFamily: "Times-Bold",
    fontSize: 18,
    lineHeight: 1.2,
    color: pdfColors.ink,
    marginBottom: 9,
  },
  h3: {
    fontFamily: "Times-Bold",
    fontSize: 13,
    color: pdfColors.volcanicDark,
    marginBottom: 6,
  },
  lead: {
    fontSize: 12,
    lineHeight: 1.7,
    color: pdfColors.text,
    marginBottom: 17,
  },
  paragraph: {
    fontSize: 10.4,
    lineHeight: 1.75,
    color: pdfColors.text,
    marginBottom: 10,
  },
  mutedText: {
    color: pdfColors.muted,
  },
  section: {
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: pdfColors.line,
  },
  slimRule: {
    height: 1,
    backgroundColor: pdfColors.line,
    marginTop: 14,
    marginBottom: 14,
  },
  accentLine: {
    width: 42,
    height: 2,
    backgroundColor: pdfColors.gold,
    marginBottom: 14,
  },
  indexRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 11,
    paddingBottom: 11,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.lineSoft,
  },
  indexNumber: {
    width: 32,
    color: pdfColors.gold,
    fontSize: 9,
    letterSpacing: 1,
  },
  indexTitle: {
    flex: 1,
    fontFamily: "Times-Roman",
    fontSize: 14,
    color: pdfColors.ink,
  },
  heroImage: {
    width: "100%",
    height: 178,
    objectFit: "cover",
    marginTop: 16,
  },
  wideImage: {
    width: "100%",
    height: 138,
    objectFit: "cover",
  },
  imageContain: {
    width: "100%",
    height: 178,
    objectFit: "contain",
    backgroundColor: pdfColors.sand,
  },
  imageCaption: {
    marginTop: 6,
    color: pdfColors.muted,
    fontSize: 8.5,
    lineHeight: 1.35,
  },
  twoColumns: {
    flexDirection: "row",
    marginTop: 14,
  },
  columnLeft: {
    width: "48%",
    marginRight: "4%",
  },
  columnRight: {
    width: "48%",
  },
  highlightBlock: {
    marginTop: 16,
    paddingTop: 14,
    paddingBottom: 4,
    borderTopWidth: 1,
    borderTopColor: pdfColors.lineSoft,
  },
  bulletRow: {
    flexDirection: "row",
    marginBottom: 7,
  },
  bulletDot: {
    width: 9,
    color: pdfColors.gold,
    fontSize: 12,
    lineHeight: 1.4,
  },
  bulletText: {
    flex: 1,
    color: pdfColors.text,
    fontSize: 9.6,
    lineHeight: 1.55,
  },
  infoBand: {
    marginTop: 14,
    paddingTop: 12,
    paddingRight: 14,
    paddingBottom: 12,
    paddingLeft: 14,
    borderLeftWidth: 2,
    borderLeftColor: pdfColors.gold,
    backgroundColor: pdfColors.sand,
  },
  phaseHeader: {
    marginBottom: 18,
  },
  phaseNumber: {
    color: pdfColors.salitre,
    fontSize: 9,
    letterSpacing: 1.7,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  phaseTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  phaseBadge: {
    width: 52,
    marginRight: 16,
    paddingTop: 8,
    paddingBottom: 8,
    textAlign: "center",
    color: pdfColors.white,
    backgroundColor: pdfColors.volcanicDark,
    fontFamily: "Times-Bold",
    fontSize: 18,
  },
  phaseTitle: {
    flex: 1,
    fontFamily: "Times-Bold",
    fontSize: 27,
    lineHeight: 1.12,
    color: pdfColors.ink,
  },
  subsection: {
    marginTop: 13,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: pdfColors.lineSoft,
  },
  imageGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 14,
  },
  imageGridItem: {
    width: "31.6%",
    marginRight: "2.5%",
    marginBottom: 12,
  },
  imageGridItemLast: {
    marginRight: 0,
  },
  imageThumb: {
    width: "100%",
    height: 82,
    objectFit: "cover",
  },
  table: {
    marginTop: 13,
    borderTopWidth: 1,
    borderTopColor: pdfColors.line,
    borderLeftWidth: 1,
    borderLeftColor: pdfColors.line,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: pdfColors.sand,
  },
  tableRow: {
    flexDirection: "row",
  },
  tableCell: {
    paddingTop: 7,
    paddingRight: 7,
    paddingBottom: 7,
    paddingLeft: 7,
    borderRightWidth: 1,
    borderRightColor: pdfColors.line,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.line,
    fontSize: 8.8,
    lineHeight: 1.4,
  },
  tableHeadCell: {
    color: pdfColors.volcanicDark,
    fontFamily: "Helvetica-Bold",
    fontSize: 8,
    textTransform: "uppercase",
  },
  menuBlock: {
    marginTop: 12,
    paddingTop: 10,
    paddingBottom: 10,
    borderTopWidth: 1,
    borderTopColor: pdfColors.lineSoft,
  },
  menuTitle: {
    fontFamily: "Times-Bold",
    fontSize: 13,
    color: pdfColors.ink,
    marginBottom: 3,
  },
  menuMeta: {
    color: pdfColors.gold,
    fontSize: 8.5,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 5,
  },
  dishBlock: {
    width: "48%",
    marginRight: "4%",
    marginBottom: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.lineSoft,
  },
  dishBlockEven: {
    marginRight: 0,
  },
  dishImage: {
    width: "100%",
    height: 82,
    objectFit: "cover",
    marginBottom: 8,
  },
  dishName: {
    fontFamily: "Times-Bold",
    fontSize: 12,
    color: pdfColors.ink,
    marginBottom: 4,
  },
  dishMeta: {
    fontSize: 7.7,
    color: pdfColors.salitre,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 5,
  },
  dishText: {
    fontSize: 8.7,
    lineHeight: 1.45,
    color: pdfColors.text,
  },
  dafoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 13,
  },
  dafoItem: {
    width: "48%",
    marginRight: "4%",
    marginBottom: 12,
    paddingTop: 10,
    borderTopWidth: 2,
    borderTopColor: pdfColors.salitre,
  },
  dafoItemEven: {
    marginRight: 0,
  },
});
