/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as ProyectoRouteImport } from './routes/proyecto'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MenusRouteImport } from './routes/menus'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ExperienciaRouteImport } from './routes/experiencia'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ConocenosRouteImport } from './routes/conocenos'
import { Route as CodigosQrRouteImport } from './routes/codigos-qr'
import { Route as CartaDigitalRouteImport } from './routes/carta-digital'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProyectoIndexRouteImport } from './routes/proyecto.index'
import { Route as ProyectoTecnologiasGastronomicasTempRouteImport } from './routes/proyecto.tecnologias-gastronomicas-temp'
import { Route as ProyectoPresentacionRouteImport } from './routes/proyecto.presentacion'
import { Route as ProyectoFase4DocumentacionPresentacionRouteImport } from './routes/proyecto.fase-4-documentacion-presentacion'
import { Route as ProyectoFase3DesarrolloTecnologicoImplementacionRouteImport } from './routes/proyecto.fase-3-desarrollo-tecnologico-implementacion'
import { Route as ProyectoFase2DisenoCartaContenidoRouteImport } from './routes/proyecto.fase-2-diseno-carta-contenido'
import { Route as ProyectoFase1ConceptualizacionFundamentacionRouteImport } from './routes/proyecto.fase-1-conceptualizacion-fundamentacion'
import { Route as ProyectoEstructuraMenusInversionTempRouteImport } from './routes/proyecto.estructura-menus-inversion-temp'
import { Route as ProyectoConceptualizacionFundamentacionTempRouteImport } from './routes/proyecto.conceptualizacion-fundamentacion-temp'
import { Route as CartaDigitalDishIdRouteImport } from './routes/carta-digital.$dishId'

const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoRoute = ProyectoRouteImport.update({
  id: '/proyecto',
  path: '/proyecto',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusRoute = MenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ConocenosRoute = ConocenosRouteImport.update({
  id: '/conocenos',
  path: '/conocenos',
  getParentRoute: () => rootRouteImport,
} as any)
const CodigosQrRoute = CodigosQrRouteImport.update({
  id: '/codigos-qr',
  path: '/codigos-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaDigitalRoute = CartaDigitalRouteImport.update({
  id: '/carta-digital',
  path: '/carta-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoIndexRoute = ProyectoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProyectoRoute,
} as any)
const ProyectoTecnologiasGastronomicasTempRoute =
  ProyectoTecnologiasGastronomicasTempRouteImport.update({
    id: '/tecnologias-gastronomicas-temp',
    path: '/tecnologias-gastronomicas-temp',
    getParentRoute: () => ProyectoRoute,
  } as any)
const ProyectoPresentacionRoute = ProyectoPresentacionRouteImport.update({
  id: '/presentacion',
  path: '/presentacion',
  getParentRoute: () => ProyectoRoute,
} as any)
const ProyectoFase4DocumentacionPresentacionRoute =
  ProyectoFase4DocumentacionPresentacionRouteImport.update({
    id: '/fase-4-documentacion-presentacion',
    path: '/fase-4-documentacion-presentacion',
    getParentRoute: () => ProyectoRoute,
  } as any)
const ProyectoFase3DesarrolloTecnologicoImplementacionRoute =
  ProyectoFase3DesarrolloTecnologicoImplementacionRouteImport.update({
    id: '/fase-3-desarrollo-tecnologico-implementacion',
    path: '/fase-3-desarrollo-tecnologico-implementacion',
    getParentRoute: () => ProyectoRoute,
  } as any)
const ProyectoFase2DisenoCartaContenidoRoute =
  ProyectoFase2DisenoCartaContenidoRouteImport.update({
    id: '/fase-2-diseno-carta-contenido',
    path: '/fase-2-diseno-carta-contenido',
    getParentRoute: () => ProyectoRoute,
  } as any)
const ProyectoFase1ConceptualizacionFundamentacionRoute =
  ProyectoFase1ConceptualizacionFundamentacionRouteImport.update({
    id: '/fase-1-conceptualizacion-fundamentacion',
    path: '/fase-1-conceptualizacion-fundamentacion',
    getParentRoute: () => ProyectoRoute,
  } as any)
const ProyectoEstructuraMenusInversionTempRoute =
  ProyectoEstructuraMenusInversionTempRouteImport.update({
    id: '/estructura-menus-inversion-temp',
    path: '/estructura-menus-inversion-temp',
    getParentRoute: () => ProyectoRoute,
  } as any)
const ProyectoConceptualizacionFundamentacionTempRoute =
  ProyectoConceptualizacionFundamentacionTempRouteImport.update({
    id: '/conceptualizacion-fundamentacion-temp',
    path: '/conceptualizacion-fundamentacion-temp',
    getParentRoute: () => ProyectoRoute,
  } as any)
const CartaDigitalDishIdRoute = CartaDigitalDishIdRouteImport.update({
  id: '/$dishId',
  path: '/$dishId',
  getParentRoute: () => CartaDigitalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carta-digital': typeof CartaDigitalRouteWithChildren
  '/codigos-qr': typeof CodigosQrRoute
  '/conocenos': typeof ConocenosRoute
  '/contacto': typeof ContactoRoute
  '/experiencia': typeof ExperienciaRoute
  '/galeria': typeof GaleriaRoute
  '/menus': typeof MenusRoute
  '/pedidos': typeof PedidosRoute
  '/proyecto': typeof ProyectoRouteWithChildren
  '/reservas': typeof ReservasRoute
  '/carta-digital/$dishId': typeof CartaDigitalDishIdRoute
  '/proyecto/conceptualizacion-fundamentacion-temp': typeof ProyectoConceptualizacionFundamentacionTempRoute
  '/proyecto/estructura-menus-inversion-temp': typeof ProyectoEstructuraMenusInversionTempRoute
  '/proyecto/fase-1-conceptualizacion-fundamentacion': typeof ProyectoFase1ConceptualizacionFundamentacionRoute
  '/proyecto/fase-2-diseno-carta-contenido': typeof ProyectoFase2DisenoCartaContenidoRoute
  '/proyecto/fase-3-desarrollo-tecnologico-implementacion': typeof ProyectoFase3DesarrolloTecnologicoImplementacionRoute
  '/proyecto/fase-4-documentacion-presentacion': typeof ProyectoFase4DocumentacionPresentacionRoute
  '/proyecto/presentacion': typeof ProyectoPresentacionRoute
  '/proyecto/tecnologias-gastronomicas-temp': typeof ProyectoTecnologiasGastronomicasTempRoute
  '/proyecto/': typeof ProyectoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carta-digital': typeof CartaDigitalRouteWithChildren
  '/codigos-qr': typeof CodigosQrRoute
  '/conocenos': typeof ConocenosRoute
  '/contacto': typeof ContactoRoute
  '/experiencia': typeof ExperienciaRoute
  '/galeria': typeof GaleriaRoute
  '/menus': typeof MenusRoute
  '/pedidos': typeof PedidosRoute
  '/reservas': typeof ReservasRoute
  '/carta-digital/$dishId': typeof CartaDigitalDishIdRoute
  '/proyecto/conceptualizacion-fundamentacion-temp': typeof ProyectoConceptualizacionFundamentacionTempRoute
  '/proyecto/estructura-menus-inversion-temp': typeof ProyectoEstructuraMenusInversionTempRoute
  '/proyecto/fase-1-conceptualizacion-fundamentacion': typeof ProyectoFase1ConceptualizacionFundamentacionRoute
  '/proyecto/fase-2-diseno-carta-contenido': typeof ProyectoFase2DisenoCartaContenidoRoute
  '/proyecto/fase-3-desarrollo-tecnologico-implementacion': typeof ProyectoFase3DesarrolloTecnologicoImplementacionRoute
  '/proyecto/fase-4-documentacion-presentacion': typeof ProyectoFase4DocumentacionPresentacionRoute
  '/proyecto/presentacion': typeof ProyectoPresentacionRoute
  '/proyecto/tecnologias-gastronomicas-temp': typeof ProyectoTecnologiasGastronomicasTempRoute
  '/proyecto': typeof ProyectoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carta-digital': typeof CartaDigitalRouteWithChildren
  '/codigos-qr': typeof CodigosQrRoute
  '/conocenos': typeof ConocenosRoute
  '/contacto': typeof ContactoRoute
  '/experiencia': typeof ExperienciaRoute
  '/galeria': typeof GaleriaRoute
  '/menus': typeof MenusRoute
  '/pedidos': typeof PedidosRoute
  '/proyecto': typeof ProyectoRouteWithChildren
  '/reservas': typeof ReservasRoute
  '/carta-digital/$dishId': typeof CartaDigitalDishIdRoute
  '/proyecto/conceptualizacion-fundamentacion-temp': typeof ProyectoConceptualizacionFundamentacionTempRoute
  '/proyecto/estructura-menus-inversion-temp': typeof ProyectoEstructuraMenusInversionTempRoute
  '/proyecto/fase-1-conceptualizacion-fundamentacion': typeof ProyectoFase1ConceptualizacionFundamentacionRoute
  '/proyecto/fase-2-diseno-carta-contenido': typeof ProyectoFase2DisenoCartaContenidoRoute
  '/proyecto/fase-3-desarrollo-tecnologico-implementacion': typeof ProyectoFase3DesarrolloTecnologicoImplementacionRoute
  '/proyecto/fase-4-documentacion-presentacion': typeof ProyectoFase4DocumentacionPresentacionRoute
  '/proyecto/presentacion': typeof ProyectoPresentacionRoute
  '/proyecto/tecnologias-gastronomicas-temp': typeof ProyectoTecnologiasGastronomicasTempRoute
  '/proyecto/': typeof ProyectoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carta-digital'
    | '/codigos-qr'
    | '/conocenos'
    | '/contacto'
    | '/experiencia'
    | '/galeria'
    | '/menus'
    | '/pedidos'
    | '/proyecto'
    | '/reservas'
    | '/carta-digital/$dishId'
    | '/proyecto/conceptualizacion-fundamentacion-temp'
    | '/proyecto/estructura-menus-inversion-temp'
    | '/proyecto/fase-1-conceptualizacion-fundamentacion'
    | '/proyecto/fase-2-diseno-carta-contenido'
    | '/proyecto/fase-3-desarrollo-tecnologico-implementacion'
    | '/proyecto/fase-4-documentacion-presentacion'
    | '/proyecto/presentacion'
    | '/proyecto/tecnologias-gastronomicas-temp'
    | '/proyecto/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carta-digital'
    | '/codigos-qr'
    | '/conocenos'
    | '/contacto'
    | '/experiencia'
    | '/galeria'
    | '/menus'
    | '/pedidos'
    | '/reservas'
    | '/carta-digital/$dishId'
    | '/proyecto/conceptualizacion-fundamentacion-temp'
    | '/proyecto/estructura-menus-inversion-temp'
    | '/proyecto/fase-1-conceptualizacion-fundamentacion'
    | '/proyecto/fase-2-diseno-carta-contenido'
    | '/proyecto/fase-3-desarrollo-tecnologico-implementacion'
    | '/proyecto/fase-4-documentacion-presentacion'
    | '/proyecto/presentacion'
    | '/proyecto/tecnologias-gastronomicas-temp'
    | '/proyecto'
  id:
    | '__root__'
    | '/'
    | '/carta-digital'
    | '/codigos-qr'
    | '/conocenos'
    | '/contacto'
    | '/experiencia'
    | '/galeria'
    | '/menus'
    | '/pedidos'
    | '/proyecto'
    | '/reservas'
    | '/carta-digital/$dishId'
    | '/proyecto/conceptualizacion-fundamentacion-temp'
    | '/proyecto/estructura-menus-inversion-temp'
    | '/proyecto/fase-1-conceptualizacion-fundamentacion'
    | '/proyecto/fase-2-diseno-carta-contenido'
    | '/proyecto/fase-3-desarrollo-tecnologico-implementacion'
    | '/proyecto/fase-4-documentacion-presentacion'
    | '/proyecto/presentacion'
    | '/proyecto/tecnologias-gastronomicas-temp'
    | '/proyecto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartaDigitalRoute: typeof CartaDigitalRouteWithChildren
  CodigosQrRoute: typeof CodigosQrRoute
  ConocenosRoute: typeof ConocenosRoute
  ContactoRoute: typeof ContactoRoute
  ExperienciaRoute: typeof ExperienciaRoute
  GaleriaRoute: typeof GaleriaRoute
  MenusRoute: typeof MenusRoute
  PedidosRoute: typeof PedidosRoute
  ProyectoRoute: typeof ProyectoRouteWithChildren
  ReservasRoute: typeof ReservasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto': {
      id: '/proyecto'
      path: '/proyecto'
      fullPath: '/proyecto'
      preLoaderRoute: typeof ProyectoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menus': {
      id: '/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof MenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia': {
      id: '/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conocenos': {
      id: '/conocenos'
      path: '/conocenos'
      fullPath: '/conocenos'
      preLoaderRoute: typeof ConocenosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codigos-qr': {
      id: '/codigos-qr'
      path: '/codigos-qr'
      fullPath: '/codigos-qr'
      preLoaderRoute: typeof CodigosQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta-digital': {
      id: '/carta-digital'
      path: '/carta-digital'
      fullPath: '/carta-digital'
      preLoaderRoute: typeof CartaDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto/': {
      id: '/proyecto/'
      path: '/'
      fullPath: '/proyecto/'
      preLoaderRoute: typeof ProyectoIndexRouteImport
      parentRoute: typeof ProyectoRoute
    }
    '/proyecto/tecnologias-gastronomicas-temp': {
      id: '/proyecto/tecnologias-gastronomicas-temp'
      path: '/tecnologias-gastronomicas-temp'
      fullPath: '/proyecto/tecnologias-gastronomicas-temp'
      preLoaderRoute: typeof ProyectoTecnologiasGastronomicasTempRouteImport
      parentRoute: typeof ProyectoRoute
    }
    '/proyecto/presentacion': {
      id: '/proyecto/presentacion'
      path: '/presentacion'
      fullPath: '/proyecto/presentacion'
      preLoaderRoute: typeof ProyectoPresentacionRouteImport
      parentRoute: typeof ProyectoRoute
    }
    '/proyecto/fase-4-documentacion-presentacion': {
      id: '/proyecto/fase-4-documentacion-presentacion'
      path: '/fase-4-documentacion-presentacion'
      fullPath: '/proyecto/fase-4-documentacion-presentacion'
      preLoaderRoute: typeof ProyectoFase4DocumentacionPresentacionRouteImport
      parentRoute: typeof ProyectoRoute
    }
    '/proyecto/fase-3-desarrollo-tecnologico-implementacion': {
      id: '/proyecto/fase-3-desarrollo-tecnologico-implementacion'
      path: '/fase-3-desarrollo-tecnologico-implementacion'
      fullPath: '/proyecto/fase-3-desarrollo-tecnologico-implementacion'
      preLoaderRoute: typeof ProyectoFase3DesarrolloTecnologicoImplementacionRouteImport
      parentRoute: typeof ProyectoRoute
    }
    '/proyecto/fase-2-diseno-carta-contenido': {
      id: '/proyecto/fase-2-diseno-carta-contenido'
      path: '/fase-2-diseno-carta-contenido'
      fullPath: '/proyecto/fase-2-diseno-carta-contenido'
      preLoaderRoute: typeof ProyectoFase2DisenoCartaContenidoRouteImport
      parentRoute: typeof ProyectoRoute
    }
    '/proyecto/fase-1-conceptualizacion-fundamentacion': {
      id: '/proyecto/fase-1-conceptualizacion-fundamentacion'
      path: '/fase-1-conceptualizacion-fundamentacion'
      fullPath: '/proyecto/fase-1-conceptualizacion-fundamentacion'
      preLoaderRoute: typeof ProyectoFase1ConceptualizacionFundamentacionRouteImport
      parentRoute: typeof ProyectoRoute
    }
    '/proyecto/estructura-menus-inversion-temp': {
      id: '/proyecto/estructura-menus-inversion-temp'
      path: '/estructura-menus-inversion-temp'
      fullPath: '/proyecto/estructura-menus-inversion-temp'
      preLoaderRoute: typeof ProyectoEstructuraMenusInversionTempRouteImport
      parentRoute: typeof ProyectoRoute
    }
    '/proyecto/conceptualizacion-fundamentacion-temp': {
      id: '/proyecto/conceptualizacion-fundamentacion-temp'
      path: '/conceptualizacion-fundamentacion-temp'
      fullPath: '/proyecto/conceptualizacion-fundamentacion-temp'
      preLoaderRoute: typeof ProyectoConceptualizacionFundamentacionTempRouteImport
      parentRoute: typeof ProyectoRoute
    }
    '/carta-digital/$dishId': {
      id: '/carta-digital/$dishId'
      path: '/$dishId'
      fullPath: '/carta-digital/$dishId'
      preLoaderRoute: typeof CartaDigitalDishIdRouteImport
      parentRoute: typeof CartaDigitalRoute
    }
  }
}

interface CartaDigitalRouteChildren {
  CartaDigitalDishIdRoute: typeof CartaDigitalDishIdRoute
}

const CartaDigitalRouteChildren: CartaDigitalRouteChildren = {
  CartaDigitalDishIdRoute: CartaDigitalDishIdRoute,
}

const CartaDigitalRouteWithChildren = CartaDigitalRoute._addFileChildren(
  CartaDigitalRouteChildren,
)

interface ProyectoRouteChildren {
  ProyectoConceptualizacionFundamentacionTempRoute: typeof ProyectoConceptualizacionFundamentacionTempRoute
  ProyectoEstructuraMenusInversionTempRoute: typeof ProyectoEstructuraMenusInversionTempRoute
  ProyectoFase1ConceptualizacionFundamentacionRoute: typeof ProyectoFase1ConceptualizacionFundamentacionRoute
  ProyectoFase2DisenoCartaContenidoRoute: typeof ProyectoFase2DisenoCartaContenidoRoute
  ProyectoFase3DesarrolloTecnologicoImplementacionRoute: typeof ProyectoFase3DesarrolloTecnologicoImplementacionRoute
  ProyectoFase4DocumentacionPresentacionRoute: typeof ProyectoFase4DocumentacionPresentacionRoute
  ProyectoPresentacionRoute: typeof ProyectoPresentacionRoute
  ProyectoTecnologiasGastronomicasTempRoute: typeof ProyectoTecnologiasGastronomicasTempRoute
  ProyectoIndexRoute: typeof ProyectoIndexRoute
}

const ProyectoRouteChildren: ProyectoRouteChildren = {
  ProyectoConceptualizacionFundamentacionTempRoute:
    ProyectoConceptualizacionFundamentacionTempRoute,
  ProyectoEstructuraMenusInversionTempRoute:
    ProyectoEstructuraMenusInversionTempRoute,
  ProyectoFase1ConceptualizacionFundamentacionRoute:
    ProyectoFase1ConceptualizacionFundamentacionRoute,
  ProyectoFase2DisenoCartaContenidoRoute:
    ProyectoFase2DisenoCartaContenidoRoute,
  ProyectoFase3DesarrolloTecnologicoImplementacionRoute:
    ProyectoFase3DesarrolloTecnologicoImplementacionRoute,
  ProyectoFase4DocumentacionPresentacionRoute:
    ProyectoFase4DocumentacionPresentacionRoute,
  ProyectoPresentacionRoute: ProyectoPresentacionRoute,
  ProyectoTecnologiasGastronomicasTempRoute:
    ProyectoTecnologiasGastronomicasTempRoute,
  ProyectoIndexRoute: ProyectoIndexRoute,
}

const ProyectoRouteWithChildren = ProyectoRoute._addFileChildren(
  ProyectoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartaDigitalRoute: CartaDigitalRouteWithChildren,
  CodigosQrRoute: CodigosQrRoute,
  ConocenosRoute: ConocenosRoute,
  ContactoRoute: ContactoRoute,
  ExperienciaRoute: ExperienciaRoute,
  GaleriaRoute: GaleriaRoute,
  MenusRoute: MenusRoute,
  PedidosRoute: PedidosRoute,
  ProyectoRoute: ProyectoRouteWithChildren,
  ReservasRoute: ReservasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
